In [1]:
%load_ext autoreload
%autoreload 2

In [19]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('./merged_eval_results/exploited/test.csv')

In [20]:
del df['Unnamed: 0']

In [21]:
# Find the maximum value in each row
max_values = df.max(axis=1)

# Find the column index (name) of the maximum value in each row
argmax_columns = df.idxmax(axis=1)

# Print or store the results
print("Maximum values in each row:\n", max_values)
print("Column indices (names) of maximum values in each row:\n", argmax_columns)

Maximum values in each row:
 0     0.998257
1     0.998165
2     0.998217
3     0.998232
4     0.998322
        ...
95    0.997513
96    0.005029
97    0.998353
98    0.998030
99    0.997731
Length: 100, dtype: float64
Column indices (names) of maximum values in each row:
 0     temp_0.05
1     temp_0.65
2     temp_0.75
3      temp_0.8
4      topp_0.9
        ...
95    topp_0.95
96    temp_0.65
97     topp_0.5
98     topk_500
99       greedy
Length: 100, dtype: object

In [22]:
result_df = pd.DataFrame({
    'MaxValue': max_values,
    'ArgMaxColumn': argmax_columns
})

print(result_df)

    MaxValue ArgMaxColumn
0   0.998257    temp_0.05
1   0.998165    temp_0.65
2   0.998217    temp_0.75
3   0.998232     temp_0.8
4   0.998322     topp_0.9
..       ...          ...
95  0.997513    topp_0.95
96  0.005029    temp_0.65
97  0.998353     topp_0.5
98  0.998030     topk_500
99  0.997731       greedy

[100 rows x 2 columns]

In [23]:
result_df.to_csv("attack_setting.csv")

In [13]:
df

,greedy,temp_0.05,temp_0.1,temp_0.15,temp_0.2,temp_0.25,temp_0.3,temp_0.35,temp_0.4,temp_0.45,...,topp_0.55,topp_0.6,topp_0.65,topp_0.7,topp_0.75,topp_0.8,topp_0.85,topp_0.9,topp_0.95,topp_1.0
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
96,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
97,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
98,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
99,0.997731,0.997783,0.997783,0.997783,0.997783,0.997783,0.996294,0.996294,0.997505,0.997505,...,0.00546,0.997505,0.997505,0.004977,0.006513,0.006513,0.99602,0.996525,0.996525,0.995362